import streamlit as st

st.title("*CONCEPTOS BÁSICOS*")

st.write(" **¿Qué es un Ticker?**")
st.write("Es un código alfanumérico que indica los valores de un negocio que cotiza en una determinada bolsa de valores. Las empresas que cotizan en el mercado Nasdaq tienen tickers de cuatro letras, mientras que las que cotizan en la Bolsa de Nueva York tienen tickers de tres letras.")
st.write(" ")
st.write(" **¿Qué son los Activos Financieros?**")
st.write("Acciones, bonos, materias primas, divisas y otros activos financieros son ejemplos de activos financieros.")
st.write(" ")
st.write(" **¿Qué son las Acciones?**")
st.write("Las acciones son valores que representan una parte del capital social de una empresa. Un accionista posee una parte de la empresa y tiene derecho a un porcentaje de sus ganancias como propietario de una acción.")
st.write(" ")
st.write(" **¿Qué significa corto o posición corta en el mercado de valores?**")
st.write("Tomar una posición corta implica vender un activo que no se posee con la esperanza de recomprarlo más tarde a un precio más bajo. Es una estrategia para beneficiarse de la disminución del valor del activo.")
st.write(" ")
st.write(" **¿Cómo afectan los dividendos a los inversionistas en acciones?**")
st.write("Los dividendos son pagos de las ganancias de una empresa a sus accionistas. Afectan positivamente a los inversionistas, proporcionando ingresos regulares y, a veces, indicando la salud financiera de la empresa")
st.write(" ")
st.write(" **¿Cuál es la importancia del análisis técnico en la inversión bursátil?**")
st.write("El análisis técnico examina patrones y tendencias pasadas en gráficos de precios para prever movimientos futuros. Es relevante para los inversores que buscan tomar decisiones basadas en el comportamiento histórico del mercado.")
st.write(" ")
st.write(" **¿Cómo afecta la oferta y la demanda al precio de las acciones?**")
st.write("Si la demanda de una acción supera la oferta, el precio tiende a subir, y viceversa. La oferta y la demanda son fundamentales para determinar los precios en el mercado de valores.")
st.write(" ")
st.write(" ")
st.write(" CRÉDITOS DEL SIMULADOR")
st.write("Líder de proyecto: Jesús García - 3103963783")
st.write("Desarrollador backend: Alessandro Villanueva - 3002252099")
st.write("Desarrollador frontend: Santiago Román - 3154070811")
